### ISSUE TITLE
Minor error on website: Realtime line chart example

### ISSUE THREAD

**Issue by ljowen** [fastly/epoch#147]
```html
<div id="lineChart" style="width: 800px; height: 200px"></div>
<script>
  $('#lineChart').epoch({
    type: 'time.bar',
    data: lineChartData
  });
</script>
```

Should be
```html
<div id="lineChart" style="width: 800px; height: 200px"></div>
<script>
  $('#lineChart').epoch({
    type: 'time.line',
    data: lineChartData
  });
</script>
```

**Comment by aspires** [comment]
Hi @ljowen! If you want, you can file the pull request yourself and get credit for the fix :)

**Comment by ljowen** [comment]
Hi @aspires I may be wrong here but I was referring to the project site: http://fastly.github.io/epoch/ 
Which appears to be separate from this repo.

**Comment by aspires** [comment]
Actually, that site lives in the [gh-pages branch](https://github.com/fastly/epoch/tree/gh-pages) of the repo. So, the source is there, just not on the master branch.

**Comment by ljowen** [comment]
Thanks, issued pull request with change

**Comment by ljowen** [comment]
Merged
