### ISSUE TITLE
Allow Simple Data Formats

### ISSUE THREAD

**Issue by rsandor** [fastly/epoch#18]
For ease of implementation we chose to have set data formats for each of the types of plot. This can be a bit painful for simpler data (especially for time series data). Consider allowing each of the plots to accept multiple formats for the data. 

I'd like to allow for more "flat" data to be used without having to explicitly specify the layer structure. For instance, instead of having to do this:

``` javascript
data = [
    { label: 'Layer 1', values: [ {time: 0, y: 0}, ... ] }
]
```

one could simply define the same single layer data set like so:

``` javascript
data = [ {time: 0, y: 0}, ... ]
```

Additionally it would be nice to allow for a series of basic numbers:

``` javascript
data = [ 0, 1, 2, 3, 20302 ]
```

For basic plots we could simply use the index as the x value. For real-time plots it's less nice since the time parameter expects a unix timestamp. Perhaps we could just count back from the current second in the browser?

Either way having simpler data formats should make it easier to get up and running with the library. And one can always use a more formal format as needed.

**Comment by eSandle** [comment]
Yes
