### ISSUE TITLE
Uncaught TypeError: Cannot read property 'visible' of undefined(…) epoch.js:3024

### ISSUE THREAD

**Issue by webmutation** [fastly/epoch#232]
I get this error whenever the chart is not visible... meaing is not in visible area, scroll up or down.

Uncaught TypeError: Cannot read property 'visible' of undefined(…)
epoch.js:3024

**Comment by ianchildress** [comment]
What was the solution here?

**Comment by webmutation** [comment]
make sure the chart is visible added a check to that funcion, not really great solution... there should be a better fix but i did not tackle it.
