### ISSUE TITLE
Seems to require jQuery, yet doesn't seem explicit about it

### ISSUE THREAD

**Issue by kbadk** [fastly/epoch#238]
I'm trying to get a simple example working with the [Getting Started guide](https://epochjs.github.io/epoch/getting-started/). The page lists required scripts

```html
<script src="js/d3.min.js"></script>
<script src="js/epoch.min.js"></script>
```

But then goes on to use jQuery. All examples in the documentation seems to use jQuery and I can't find a link to the API anywhere, so I can figure out how to create a chart without jQuery.

Is jQuery required? If so, the documentation ought to say so. If not, the documentation should (in my opinion) include examples without jQuery – not everybody is willing to use jQuery. A link to an API documentation would also do the trick.

**Comment by 0x3W** [comment]
Yes, in fact You need the following line 

    <script src="http://code.jquery.com/jquery-3.1.0.slim.min.js"></script>

And make sure You use v3 of d3 as Epoch breaks compatibility after v3, current is v5 though.    

    <script src="http://d3js.org/d3.v3.js" charset="utf-8"></script>

**Comment by fjeddy** [comment]
This needs to be in the docs. Specially the part about d3 v3 being the requirement. Seriously!

**Comment by tricoos** [comment]
Can you please specifiy that explicitly? This library might not only be used on a website but on other systems where jQuery is not an option.
